### ISSUE TITLE
Feature request - ability to specify LinePattern in the LineStyle.Create node

### ISSUE THREAD

**Issue by des-hourihane** [ThomasMahon/bimorphNodes#1]
Hi

I'm using your LineStyle.Create node to make multiple styles by passing a Spreadsheet through the node - a table of the individual settings for each GraphicsStyle.

I am currently trying to build a custom node with an embedded Python script to change the LinePatternElement for each ('associated with each'? unsure of correct Revit API term). It seems like it would be a very useful thing to be able to do in a single step.

Thanks for the package in any case.

**Comment by ThomasMahon** [comment]
It is possible in the Revit API from 2017 and above using the SetLinePatternId() method. The current version of BimorphNodes is built on 2016 which doesn't include the ability to set line patterns! However, version 2.2 which will be released this month is built on the new API and will include the linePattern input:

![image](https://user-images.githubusercontent.com/18601851/34785633-a49931be-f629-11e7-92e5-896d3d878690.png)
